### ISSUE TITLE
nufft1d3 failed when device id is 1

### ISSUE THREAD

**Issue by PascalCarrivain** [flatironinstitute/finufft#730]
Dear all,

I run the following code:

```python
from cufinufft import nufft1d3
import cupy as cp

N = 16
cp.random.seed(1)

cp.cuda.runtime.setDevice(0)
x = cp.random.randn(N) + 0j
print(x.device)
samples = 2 * cp.pi * cp.random.randn(N)
frequencies = N * cp.random.randn(N)
y = nufft1d3(samples, x + 0j, frequencies, out=None)
print(y)

cp.cuda.runtime.setDevice(1)
x = cp.random.randn(N) + 0j
print(x.device)
samples = 2 * cp.pi * cp.random.randn(N)
frequencies = N * cp.random.randn(N)
y = nufft1d3(samples, x + 0j, frequencies, out=None)
print(y)
```

and I get the result:

```bash
<CUDA Device 0>
[ 1.42001093+1.12570819j  0.98541926-1.86291755j  1.04580728-2.23953218j
  2.36501042-0.80201554j -0.72972935-2.34752703j -2.57463962+0.52595776j
 -3.1934722 +1.96059487j -4.22668786-1.37803546j  3.32958136+2.91536727j
  0.67993737-0.04113419j  0.29916902-2.88515836j -2.26970584+0.34839626j
 -3.71098785+0.07255863j  0.82474972+1.3699282j  -0.68776326+0.94059609j
  0.5670202 -3.40429551j]
<CUDA Device 1>
terminate called after throwing an instance of 'thrust::THRUST_200302_500_600_700_800_NS::system::system_error'
  what():  exclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted
```

Using device id 0 does work while using device id 1 does not work.

Did I miss something?

Thank you for your help.

Pascal

**version:**

cufinufft                     2.4.1    
cupy-cuda12x            13.6.0
CUDA version            12.4

**Comment by lu1and10** [comment]
Hi @PascalCarrivain 
By default, cufinufft choose device id 0, to use device 1, you may try `y = nufft1d3(samples, x + 0j, frequencies, out=None, gpu_device_id=1)` to see if it works.

**Comment by PascalCarrivain** [comment]
Hi @lu1and10 I tried it and it works.
Therefore, I conclude cufinufft does not infer CUDA device id from arguments.
Thank you!

**Comment by lu1and10** [comment]
> Therefore, I conclude cufinufft does not infer CUDA device id from arguments.

Currently it can't infer from inputs. It will be a nice feature that device can be inferred from inputs.

**Comment by DiamonDinoia** [comment]
Closing because the outstanding issue is a duplicate of #420.

Maybe worth pumping the issue up.
